# Header
menu:
  首页: /
  # 前端: /categories/front-end
  # 后端: /categories/back-end
  标签: /tags
  归档: /archives
  # 订阅: /atom.xml
  关于: /about

# Content
excerpt_link: 阅读更多
content_max_width: 800px

# Sidebar
author:
  name: 汽车云技术团队
  work: Web &amp; Native Developer
  location: Beijing, China
  avatar_url: /images/avatar.png

# Links:
# links:
#   - svg: ./source/svg/_github.svg
#     url: https://github.com/sanonz
#   - svg: ./source/svg/_more.svg
#     url: http://weibo.com/sanonz
#   - svg: ./source/svg/_twitter.svg
#     url: https://twitter.com/sanonze


# github comment 
git_commit:
  enable: true
  client_id: 814115adcfdf958f7124
  client_secret: e0e03b20fe5801d1e91a7b4f02024e0c7e548a47
  repo: blog-comment
  owner: aslinwang
  admin:
    - aslinwang
  per_page: 10


# 百度统计
# baidu:
#   id: e4027971a230b210f4671f485b33846a

# Miscellaneous
# rss: /atom.xml
favicon: /images/favicon.ico
